# SPDX-FileCopyrightText: none
# SPDX-License-Identifier: CC0-1.0

Dependencies:
 - 'on': ['Linux', 'FreeBSD', 'Windows']
   'require':
    'frameworks/extra-cmake-modules': '@same'
    'frameworks/kitemviews': '@same'
    'frameworks/kcoreaddons': '@same'
    'frameworks/ki18n': '@same'
    'frameworks/kxmlgui': '@same'
    'frameworks/kirigami': '@same'
    'frameworks/kio': '@same' # CommandLauncherJob, this will get moved to KService

Options:
 test-before-installing: True
 require-passing-tests-on: ['Linux', 'FreeBSD', 'Windows']
 run-qmllint: true
