Dependencies:
- 'on': ['Linux', 'FreeBSD', 'Windows']
  'require':
    'frameworks/extra-cmake-modules': '@same'
    'frameworks/kitemviews' : '@same'
    'frameworks/kcoreaddons' : '@same'
    'frameworks/ki18n' : '@same'
    'frameworks/kiconthemes' : '@same'
    'frameworks/kxmlgui' : '@same'
    'frameworks/kactivities' : '@same'
    'frameworks/kwindowsystem' : '@same'
    'frameworks/kirigami' : '@same'

- 'on': ['Linux', 'FreeBSD']
  'require':
    'frameworks/kauth' : '@same'

Options:
  test-before-installing: True
  require-passing-tests-on: [ 'Linux', 'FreeBSD', 'Windows' ]
